### Set JwtToken
POST https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key={{API_KEY}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "returnSecureToken": true
}
> {%
    client.global.set("auth_token", response.body.idToken);
%}

### Send GET request for scheduled
POST localhost:8080/ai/recommendations/generate
Authorization: Bearer {{auth_token}}
Content-Type: application/json
