### Set JwtToken
POST https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key={{API_KEY}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "returnSecureToken": true
}
> {%
    client.global.set("auth_token", response.body.idToken);
%}

### Send GET request for scheduled
POST localhost:8080/user
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "cycle": {
    "cycleLength": 28,
    "lastPeriodStart": "2025-11-15T00:00:00.000Z"
  },
  "onboarding": {
    "completed": true,
    "completedAt": "2025-11-20T12:34:45.738Z",
    "version": "v1"
  },
  "preference": {
    "proteinTarget_g": 35,
    "sensitivities": [
      "fish"
    ],
    "vegetarian": false
  }
}
